#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd "$2"; curl -L -f -O $PROXY "$1"; cd -
}

SRC=/usr/local/src

LATEST="$(gh_releases go-gitea/gitea \
            | sort -V | grep -v dev | grep -v rc | tail -1)"
GITEA_VERSION="${LATEST#v}"
FILENAME="gitea-${GITEA_VERSION}-linux-amd64"

URL1="https://dl.gitea.io/gitea/${GITEA_VERSION}/${FILENAME}"
URL2="https://dl.gitea.io/gitea/${GITEA_VERSION}/${FILENAME}.asc"
URL3="https://raw.githubusercontent.com/go-gitea/gitea/${LATEST}/custom/conf/app.example.ini"

dl "$URL1" "$SRC"
dl "$URL2" "$SRC"
dl "$URL3" "$SRC"

gpg --import "$SRC/gitea-key.asc"
gpg --verify "$SRC/${FILENAME}.asc" "$SRC/${FILENAME}"

rm "$SRC/${FILENAME}.asc" "$SRC/gitea-key.asc"
