#!/bin/bash -ex

ADMIN_USER=gitea
ADMIN_PASS=turnkey
ADMIN_EMAIL=admin@example.org
DB_NAME=gitea
DB_USER=gitea
DB_PASS=turnkey1

SRC=/usr/local/src

useradd -M git
service mysql start

MYSQL_BATCH="mysql --batch"

# create database and user
mysqladmin create "${DB_NAME}"
$MYSQL_BATCH --execute "grant all privileges on ${DB_NAME}.* to '${DB_USER}'@localhost identified by '${DB_PASS}'; alter database ${DB_NAME} character set = utf8 collate = utf8_general_ci;"

rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/gitea /etc/nginx/sites-enabled/gitea

export USER=git HOME=/home/git GITEA_WORK_DIR=/home/git
mv $SRC/gitea-*-linux-amd64 $HOME/gitea
chmod +x /home/git/gitea
mkdir $HOME/run
mkdir -p $HOME/custom/conf
mv $SRC/app.example.ini $HOME/custom/conf/
chown -R git:git /home/git

service nginx start
service mysql start

runuser - git -c 'GITEA__security__INSTALL_LOCK=true ./gitea web --pid $HOME/tmp.pid' 2>&1 >/root/gitea-start.log &

echo "Waiting for gitea to tnstall and web server to start"
while ! grep -q 'Starting new Web server: unix:/home/git/run/gitea.sock' /root/gitea-start.log; do
    sleep 10
done

rm /root/gitea-start.log

runuser - git -c "./gitea admin user create --admin --username $ADMIN_USER --password $ADMIN_PASS --email $ADMIN_EMAIL"

kill "$(cat $HOME/tmp.pid)"
rm "$HOME/tmp.pid"

service nginx stop
service mysql stop

systemctl enable gitea
systemctl enable nginx

chown -R git:root /etc/gitea
