#!/bin/bash -ex

GH_API=https://api.github.com/repos/go-gitea/gitea/releases/latest
LATEST=$(curl -s $GH_API | grep -oP '"tag_name": "\K(.*)(?=")')
GITEA_VERSION=${LATEST#v}
ADMIN_PASS=turnkey
ADMIN_EMAIL=admin@example.org

APP_DOMAIN=www.example.com

SRC=/usr/local/src

DB_NAME=gitea
DB_USER=gitea
DB_PASS=turnkey1

useradd -M git
service mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

# create database and user
$MYSQL_ADMIN create "${DB_NAME}" --default-character-set=utf8
$MYSQL_BATCH --execute "grant all privileges on ${DB_NAME}.* to '${DB_USER}'@localhost identified by '${DB_PASS}'; alter database ${DB_NAME} character set = utf8 collate = utf8_general_ci;"

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

cd "$SRC"

FILENAME="gitea-${GITEA_VERSION}-linux-amd64"
wget "https://dl.gitea.io/gitea/${GITEA_VERSION}/${FILENAME}" "https://dl.gitea.io/gitea/${GITEA_VERSION}/${FILENAME}.asc"
gpg --keyserver keyserver.ubuntu.com --recv 0x2D9AE806EC1592E2
unset HTTP_PROXY

gpg --verify "${FILENAME}.asc" "${FILENAME}"
rm "${FILENAME}.asc"
mv "${FILENAME}" /home/git/gitea

chmod +x /home/git/gitea

rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/gitea /etc/nginx/sites-enabled/gitea

service nginx start
service mysql start

mkdir /home/git/run
chown -R git:git /home/git
export USER=git HOME=/home/git GITEA_WORK_DIR=/home/git
runuser git -c '/home/git/gitea web -c /etc/gitea/app.ini' &
WEBPID=$!

sleep 5 # wait for server to spin up


#curl -fks 'https://192.168.0.57/' --data "db_type=mysql&db_host=127.0.0.1:3306&db_user=gitea&db_passwd=Kappa123&db_name=gitea&ssl_mode=disable&charset=utf8&db_path=data%2Fgitea.db&app_name=Tey+Gitea&repo_root_path=%2Fhome%2Fgit%2Fgitea-repositories&lfs_root_path=%2Fhome%2Fgit%2Fdata%2Flfs&run_user=git&domain=192.168.0.58&ssh_port=22&http_port=80&app_url=https%3A%2F%2F192.168.0.57%2F&log_root_path=%2Fhome%2Fgit%2Flog&smtp_host=localhost&smtp_from=admin@example.com&smtp_user=&smtp_passwd=&enable_federated_avatar=on&enable_open_id_sign_in=on&enable_open_id_sign_up=on&default_allow_create_organization=on&default_enable_timetracking=on&no_reply_address=noreply.example.org&admin_name=gitea&admin_passwd=Kappa123&admin_confirm_passwd=Kappa123&admin_email=admin@example.com"

curl -fks 'https://localhost/' --data "db_type=mysql&db_host=127.0.0.1%3A3306&db_user=${DB_USER}&db_passwd=${DB_PASS}&db_name=${DB_NAME}&ssl_mode=disable&charset=utf8&db_path=data%2Fgitea.db&app_name=TurnKey+Gitea&repo_root_path=%2Fhome%2Fgit%2Fgitea-repositories&lfs_root_path=%2Fhome%2Fgit%2Fdata%2Flfs&run_user=git&domain=${APP_DOMAIN}&ssh_port=22&http_port=80&app_url=https%3A%2F%2F${APP_DOMAIN}%2F&log_root_path=%2Fhome%2Fgit%2Flog&smtp_host=localhost&smtp_from=${ADMIN_EMAIL}&smtp_user=&smtp_passwd=&enable_federated_avatar=on&enable_open_id_sign_in=on&enable_open_id_sign_up=on&default_allow_create_organization=on&default_enable_timetracking=on&no_reply_address=noreply.example.org&admin_name=gitea&admin_passwd=${ADMIN_PASS}&admin_confirm_passwd=${ADMIN_PASS}&admin_email=${ADMIN_EMAIL}"

kill ${WEBPID}

service nginx stop
service mysql stop

systemctl enable gitea
systemctl enable nginx

chown -R git:root /etc/gitea

