#!/bin/bash -e
# regenerate gitea secrets

. /etc/default/inithooks

CONF=/etc/gitea/app.ini

# secrets
KEY=$(mcookie)$(mcookie)$(mcookie)$(mcookie)
sed -i '/LFS_JWT_SECRET\|INTERNAL_TOKEN\|SECRET_KEY/d' $CONF
sed -i "/\[security\]/a \
SECRET_KEY = ${KEY}" $CONF

# mysql password
PASSWORD=$(mcookie)
sed -i "/\[database\]/,/^$/ { s/^\(PASSWD\) *=.*$/\1 = ${PASSWORD}/; }" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=gitea --pass="$PASSWORD"

systemctl restart gitea
