#!/bin/bash -e
# regenerate gitea secrets

. /etc/default/inithooks

CONF=/etc/gitea/app.ini

# secrets
gitea_update_key() {
    local item=$1
    local key=$(runuser - git -c "/home/git/gitea generate secret $item")
    echo "$item: $key"
    sed -i "\|^$item|s|=.*|= $key|" $CONF
}

gitea_update_key INTERNAL_TOKEN
gitea_update_key JWT_SECRET
gitea_update_key LFS_JWT_SECRET
gitea_update_key SECRET_KEY

# mysql password
PASSWORD=$(mcookie)
sed -i "/\[database\]/,/^$/ { s/^\(PASSWD\) *=.*$/\1 = ${PASSWORD}/; }" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=gitea --pass="$PASSWORD"

systemctl restart gitea
