#!/bin/bash -e
# set gitlab admin password, email and domain to serve

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/gitea.py --pass="$APP_PASS" --email="$APP_EMAIL" --domain="$APP_DOMAIN"

CONF=...

sed -i '/\[server\]/a \
sed -i "s/\(SECRET_KEY =\).*/\1 $(mcookie)/; s/\(DOMAIN =\).*/\1 $(domain)/"
